### ISSUE TITLE
importar librería de roles

### ISSUE THREAD

**Issue by pauloAlexisdp** [lgsilvestre/StudentTimeLine_G1#14]
instanciar roles y permisos

**Comment by SrDeLorean** [comment]
Hubo un error al crear los seeder, espesificamente el el archo UserTablesSeeder al momento de asignarle el rol al director me equivoque de nombre de rol, tenia director y era secretaria de escuela
Ademas de lo anterior encontre otro error en RolesAndPermisssions donde me equicoque al crear 2 veces el permiso create user y el read user.
Todos estos cambios fueron realizados en el push Importar libreria JWT (#15)
