### ISSUE TITLE
Instanciar usuarios de prueba

### ISSUE THREAD

**Issue by pauloAlexisdp** [lgsilvestre/StudentTimeLine_G1#16]
-realizar migración de la base de datos y crear el modelo respectivo, para posteriormente poblar la bd con usuarios de prueba

**Comment by SrDeLorean** [comment]
Se crearon 3 usuarios:
profesor: email: profesor@gmail.com   password: 12345678
administrador: email: administrador@gmail.com   password: 12345678
secretaria de escuela: email: secretariadeescuela@gmail.com   password: 12345678
