### ISSUE TITLE
implementar body de la vista registrar un usuario

### ISSUE THREAD

**Issue by pauloAlexisdp** [lgsilvestre/StudentTimeLine_G1#24]

**Comment by PinkyStyle** [comment]
Se implemento el body para el registro de usuarios. Hubo problemas con el desarrollo, tanto con el diseño como con la implementación, para lo cual @worlark ayudo guiando el diseño y dando consejos sobre como implementar los distintos elementos. Al llegar a un diseño "funcional", pero que no era lo que esperábamos, se optó por realizar ajustes en la iteración de la próxima semana.
