### ISSUE TITLE
implementar metodo de registro de usuarios

### ISSUE THREAD

**Issue by pauloAlexisdp** [lgsilvestre/StudentTimeLine_G1#25]

**Comment by worlark** [comment]
![image](https://user-images.githubusercontent.com/31330238/82768259-f28e8500-9dfb-11ea-8f6e-9ad0c5a8f9c4.png)
@pauloAlexisdp @SrDeLorean @JaaviMendez8 favor de encriptar la contraseña del usuario en el método para crear un usuario desde un administrador. <3
